app:
  host: 0.0.0.0
  port: 8080
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 30
  debug: true
  auth_table: user

database:
  host: 127.0.0.1
  port: 3306
  user: user
  name: clean_arch
  password: password
  max_idle_connections: 100
  max_open_connections: 300
  max_connection_lifetime: 300
  debug: true

auth:
  hash_salt: f1nd1ngn3m0
  signing_key: fkskkdkksdkkkd
  token_ttl: 3600