version: '3.7'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'clean_arch'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
  consul:
    container_name: "clean-consul"
    image: consul:latest
    ports:
      - 8500:8500